/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2018-06-06 18:36:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class changed_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1528261608488L));
    _jspx_dependants.put("/common.jsp", Long.valueOf(1528310117131L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1528292528280L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" ");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>TMW-Progect</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"./resource/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"./resource/css/shop-homepage.css\" rel=\"stylesheet\">");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String url = "jdbc:oracle:thin:@localhost:1521/ORCL"; 
String id = "csuser"; // 사용자계정 
String pw = "cs1234"; // 사용자계정의 패스워드 // 데이터베이스와 연동하기 위해 DriverManager에 등록한다. 
Connection con = null;
PreparedStatement ps =null;
Statement  stmt   = null;
ResultSet rs = null;
String name=(String)application.getAttribute("name");
String ID = "'"+name+"'";
String sql1="select id, emitType, sum(quantity*bottle.refund) as 공병환급금, sum(quantity*bottle.point) as 에코포인트 from waste,bottle where emitType in (select bottle from bottle) and waste.emittype=bottle.bottle and id="+ID+"group by id,emittype";
String sql2="select id, emitType as 대체여부, sum(quantity*replacement.point) as 에코포인트 from waste,replacement where emitType in (select replacement from replacement) and waste.emittype=replacement.replacement and id="+ID+"group by id,emittype";
int i=0;
try
 {
    Class.forName("oracle.jdbc.driver.OracleDriver");
    con = DriverManager.getConnection(url, id, pw);
    System.out.println("연결확인");
    
    ps=con.prepareStatement(sql1);
    rs = ps.executeQuery();

    
      out.write("\r\n");
      out.write("  ");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark fixed-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">TMW Project</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"loginsuccess.jsp\">Home\r\n");
      out.write("                <span class=\"sr-only\">(current)</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"index.jsp\">logout</a>\r\n");
      out.write("            </li>\r\n");
      out.write(" \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("      <br>\r\n");
      out.write("   <br>\r\n");
      out.write("   <br>\r\n");
      out.write("<h2 >");
      out.print(name );
      out.write("님의환급금과 에코포인트 현황 </h2>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("    ");
 
    while(rs.next()){
    	
      out.write("\r\n");
      out.write("       <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("              <div class=\"card h-100\">\r\n");
      out.write("                <a href=\"#\"><img class=\"card-img-top\" src=\"./image/");
      out.print( rs.getString(2));
      out.write(".png\" alt=\"\"></a>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h4 class=\"card-title\">\r\n");
      out.write("                    ");
      out.print( rs.getString(2));
      out.write("\r\n");
      out.write("                  </h4>\r\n");
      out.write("                  <h5> 공병환급금:");
      out.print( rs.getString(3));
      out.write("</h5>\r\n");
      out.write("                   <h5>에코포인트:");
      out.print( rs.getString(4));
      out.write("</h5>\r\n");
      out.write("                  <p class=\"card-text\"> ");
      out.print( rs.getString(1));
      out.write("의 공병환급금은");
      out.print( rs.getString(3));
      out.write("이고\r\n");
      out.write("                  에코포인트는");
      out.print( rs.getString(4));
      out.write("입니다</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
}
      out.write("\r\n");
      out.write("     ");

     ps=con.prepareStatement(sql2);
     rs = ps.executeQuery();
     while(rs.next()){
     
      out.write("<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("              <div class=\"card h-100\">\r\n");
      out.write("                <a href=\"#\"><img class=\"card-img-top\" src=\"./image/");
      out.print( rs.getString(2));
      out.write(".png\" alt=\"\"></a>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h4 class=\"card-title\">\r\n");
      out.write("                    ");
      out.print( rs.getString(2));
      out.write("\r\n");
      out.write("                  </h4>\r\n");
      out.write("                  <h5> 에코포인트:");
      out.print( rs.getString(3));
      out.write("</h5>\r\n");
      out.write("                  <p class=\"card-text\"> ");
      out.print( rs.getString(1));
      out.write('님');
      out.write('의');
      out.print( rs.getString(2));
      out.write("의 에코포인트는");
      out.print( rs.getString(3));
      out.write("입니다</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div> ");
}
  }catch(SQLException e){out.println(e);
  System.out.println("연결에러");}

      out.write("\r\n");
      out.write("     \r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write(" ");
      out.write(" <!-- Bootstrap core JavaScript -->\r\n");
      out.write("    <script src=\"./resource/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"./resource/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
